yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403csrf = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Напишите свой текст',
    )
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )
    group = models.ForeignKey(Group,
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              verbose_name='Группа',
                              related_name='posts',
                              help_text='Выберите группу'
                              )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )

    class Meta:
        ordering = ['-pub_date']
        default_related_name = 'posts'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(
        User, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField(max_length=500,
                            help_text='Напишите ваш комментарий',
                            verbose_name='Текст комментария')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата публикации')

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User, related_name='follower', on_delete=models.CASCADE)
    author = models.ForeignKey(
        User, related_name='following', on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow'
            ),
        ]

    def __str__(self):
        return f'{self.user} follows {self.author}'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['group', 'text', 'image']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Post, Group, Follow

User = get_user_model()


def paginate_page(queryset, request):
    paginator = Paginator(queryset, settings.POSTS_VALUES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(20, key_prefix='index_page')
def index(request):
    posts = Post.objects.select_related('author', 'group')
    title = 'Последние обновления на сайте'
    context = {
        'title': title,
        'posts': posts,
        'page_obj': paginate_page(posts, request),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    title = f'Записи сообщества {slug}'
    posts = group.posts.select_related('author', 'group')
    context = {
        'group': group,
        'title': title,
        'page_obj': paginate_page(posts, request),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author', 'group')
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    context = {
        'author': author,
        'page_obj': paginate_page(posts, request),
        'following': following,

    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.select_related('author')
    form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {
        'form': form,
        'is_edit': False,
    }
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', username=form.author)
    return render(request, 'posts/create_post.html/', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('posts:post_detail', post.pk)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, 'posts/create_post.html/', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user,
                                ).select_related('author', 'group')
    context = {
        'page_obj': paginate_page(posts, request),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if not Follow.objects.filter(
            user=request.user,
            author=author
    ).exists() and request.user != author:
        Follow.objects.create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user,
        author=get_object_or_404(User, username=username)
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
    <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}
                <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
    </div>
{% endif %}

{% for comment in post.comments.all %}
    <div class="media mb-4">
        <div class="media-body">
            <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                </a>
            </h5>
            <small>{{ comment.created }}</small>
            <p>
                {{ comment.text }}
            </p>
        </div>
    </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}
        Редактирование записи
    {% else %}
        Добавление новой записи
    {% endif %}
{% endblock %}
{% block content %}
    {% load user_filters %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if is_edit %}
                        Редактировать запись
                    {% else %}
                        Новая запись
                    {% endif %}
                </div>
                <div class="card-body">
                    {% include 'includes/error_control.html' %}
                    {% for field in form %}
                        {% if is_edit %}
                            <form method="post" enctype="multipart/form-data"
                                  action="{% url 'posts:post_edit' post.id %}">
                        {% else %}
                            <form method="post" enctype="multipart/form-data"
                                  action="{% url 'posts:post_create' %} ">
                        {% endif %}
                        {% csrf_token %}
                    {% endfor %}
                    {% include 'includes/common_form.html' %}
                    {% if is_edit %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Сохранить
                            </button>
                        </div>
                    {% else %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Добавить запись
                            </button>
                        </div>
                    {% endif %}
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->

{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Подписка{% endblock title %}
{% load cache %}
{% block content %}
    {% include 'includes/menu.html' with follow=True  %}
    {% for post in page_obj %}
        <div class="container-xl py-2">
            <ul>
                <li>
                    <b>Автор:</b> <a href="{% url 'posts:profile' post.author %}">
                    {% if post.author.get_full_name %}
                        {{ post.author.get_full_name }} </a>
                    {% else %}
                        {{ post.author }} </a>
                    {% endif %}
                </li>
                <li>
                    <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
                </li>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
            </ul>
            <p>{{ post.text|linebreaksbr }}</p>
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
                <hr>{% endif %}
        </div>
    {% endfor %}
    {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <div class="row text-left p-3 justify-content-center">
        <h1>
            {{ group }}
        </h1>
    </div>
    {% for post in page_obj %}
        <div class="mx-5">
            <ul>
                <li>
                    <b>Группа:</b>
                    <p>{{ group.description }}</p>
                    <b>Автор:</b> {{ post.author.get_full_name }}
                </li>
                <li>
                    <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
                </li>
                {% thumbnail post.image "1260x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            </ul>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
        {% if not forloop.last %}
            <hr>{% endif %}
    {% endfor %}
    {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock title %}
{% block content %}
    {% include 'includes/menu.html' with index=True %}
        {% for post in page_obj %}
            <div class="container-xl py-2">
                <ul>
                    <li>
                        <b>Автор:</b> <a href="{% url 'posts:profile' post.author %}">
                        {% if post.author.get_full_name %}
                            {{ post.author.get_full_name }} </a>
                        {% else %}
                            {{ post.author }} </a>
                        {% endif %}
                    </li>
                    <li>
                        <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
                    </li>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                </ul>
                <p>{{ post.text|linebreaksbr }}</p>
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                {% endif %}
                {% if not forloop.last %}
                    <hr>{% endif %}
            </div>
        {% endfor %}
        {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/paginator.html
{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        Предыдущая
                    </a>
                </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        Следующая
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                        Последняя
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Пост {{ post|truncatechars:30 }} {% endblock title %}
{% block content %}
    <main>
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                    {% if post_id.group %}
                        <li class="list-group-item">
                            Группа: {{ post.group.title }}
                            <a href="{% url 'posts:group_list' post.group.slug %}">
                                все записи группы
                            </a>
                        </li>
                    {% endif %}
                    <li class="list-group-item">
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора: <span>{{ author.posts.count }}</span>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' post.author %}">
                            все посты пользователя
                        </a>
                    </li>
                    {% if user == post.author %}
                        <li class="list-group-item">
                            <a href="{% url 'posts:post_edit' post.id %}" class="list-group-item-action">
                                Изменить пост
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "1260x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>
                <p>{{ post.text|linebreaksbr }}</p>
                {% include 'posts/comments.html' %}
                </p>
            </article>

        </div>
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
    <div class="container-xl py-2">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ author.posts.count }}</h3>
        <p>
            {% if following %}
                <a
                        class="btn btn-lg btn-light"
                        href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                    Отписаться
                </a>
            {% else %}
                <a
                        class="btn btn-lg btn-primary"
                        href="{% url 'posts:profile_follow' author.username %}" role="button">
                    Подписаться
                </a>
            {% endif %}
        </p>
        {% for post in page_obj %}
            <ul>
                <li>
                    Автор: {{ author.get_full_name }}
                    <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% thumbnail post.image "1260x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            </ul>
            <p style="text-indent: 25px;">{{ post.text|linebreaksbr }}</p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            {% if post.group %}
                <p>
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a>
                </p>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
    </div>
    {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/switcher.html
{% if user.is_authenticated %}
    <div class="container-xl py-2">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a
                        class="nav-link {% if index %}active{% endif %}"
                        href="{% url 'posts:index' %}"
                >
                    Все авторы
                </a>
            </li>
            <li class="nav-item">
                <a
                        class="nav-link {% if follow %}active{% endif %}"
                        href="{% url 'posts:follow_index' %}"
                >
                    Избранные авторы
                </a>
            </li>
        </ul>
    </div>
{% endif %}